name: kids_standalone_website
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  toml: ^0.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
